/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author manii
 */

import javax.swing.table.DefaultTableModel;
import java.sql.*;

public class FormBuku extends javax.swing.JFrame {
    
    private final DefaultTableModel model;
    private final KoneksiDatabase koneksi;
    
    /**
     * Creates new form FormBuku
     */
    public FormBuku() {
        initComponents();
        
        koneksi = new KoneksiDatabase();
        model = new DefaultTableModel();
        
        TabelDataBuku.setModel(model);
        model.addColumn("Kode Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataBuku = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        KodeBuku = new javax.swing.JLabel();
        kode_buku = new javax.swing.JTextField();
        JudulBuku = new javax.swing.JLabel();
        judul_buku = new javax.swing.JTextField();
        Pengarang = new javax.swing.JLabel();
        pengarang = new javax.swing.JTextField();
        Penerbit = new javax.swing.JLabel();
        penerbit = new javax.swing.JTextField();
        tambahBuku = new javax.swing.JButton();
        ubahBuku = new javax.swing.JButton();
        hapusBuku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabel Buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        TabelDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelDataBuku);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 530, 400));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        KodeBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        KodeBuku.setForeground(new java.awt.Color(255, 255, 255));
        KodeBuku.setText("Kode Buku");

        kode_buku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JudulBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JudulBuku.setForeground(new java.awt.Color(255, 255, 255));
        JudulBuku.setText("Judul Buku");

        judul_buku.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Pengarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pengarang.setForeground(new java.awt.Color(255, 255, 255));
        Pengarang.setText("Pengarang");

        pengarang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Penerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Penerbit.setForeground(new java.awt.Color(255, 255, 255));
        Penerbit.setText("Penerbit");

        penerbit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        penerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbitActionPerformed(evt);
            }
        });

        tambahBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahBuku.setText("Tambah");
        tambahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBukuActionPerformed(evt);
            }
        });

        ubahBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ubahBuku.setText("Ubah");
        ubahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBukuActionPerformed(evt);
            }
        });

        hapusBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hapusBuku.setText("Hapus");
        hapusBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kode_buku)
                    .addComponent(judul_buku, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(pengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KodeBuku)
                            .addComponent(JudulBuku)
                            .addComponent(Pengarang)
                            .addComponent(Penerbit)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tambahBuku)
                                .addGap(18, 18, 18)
                                .addComponent(ubahBuku)
                                .addGap(18, 18, 18)
                                .addComponent(hapusBuku)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KodeBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JudulBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pengarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Penerbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBuku)
                    .addComponent(ubahBuku)
                    .addComponent(hapusBuku))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penerbitActionPerformed

    private void tambahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBukuActionPerformed
        // TODO add your handling code here:
        koneksi.tambahBuku(
            kode_buku.getText(),
            judul_buku.getText(),
            pengarang.getText(),
            penerbit.getText()
        );
        loadData();
    }//GEN-LAST:event_tambahBukuActionPerformed

    private void ubahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBukuActionPerformed
        // TODO add your handling code here:
        koneksi.ubahBuku(
            kode_buku.getText(),
            judul_buku.getText(),
            pengarang.getText(),
            penerbit.getText()
        );
        loadData();
    }//GEN-LAST:event_ubahBukuActionPerformed

    private void hapusBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBukuActionPerformed
        // TODO add your handling code here:
        koneksi.hapusBuku(
            kode_buku.getText()
        );
        loadData();
    }//GEN-LAST:event_hapusBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormBuku().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JudulBuku;
    private javax.swing.JLabel KodeBuku;
    private javax.swing.JLabel Penerbit;
    private javax.swing.JLabel Pengarang;
    private javax.swing.JTable TabelDataBuku;
    private javax.swing.JButton hapusBuku;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judul_buku;
    private javax.swing.JTextField kode_buku;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField pengarang;
    private javax.swing.JButton tambahBuku;
    private javax.swing.JButton ubahBuku;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String query = "SELECT * FROM buku";    
        try {
            Connection con = KoneksiDatabase.getKoneksi();
            try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    Object[] obj = new Object[4];
                    obj[0] = rs.getString("kode_buku");
                    obj[1] = rs.getString("judul_buku");
                    obj[2] = rs.getString("pengarang");
                    obj[3] = rs.getString("penerbit");
                    model.addRow(obj);
                }
            }
        }
        catch(SQLException ex) {
            System.out.println("Terjadi Error");
        }
    }
}
